fix: workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,7 +4,7 @@ on:
   push:
     branches: [main]
     tags:
-      - 'v*'  # trigger GoReleaser on semantic-release tag pushes
+      - 'v*'  # Run goreleaser on version tags
 
 jobs:
   tag:
@@ -30,11 +30,11 @@ jobs:
           go install github.com/go-semantic-release/semantic-release/cmd/semantic-release@v1.20.1
           echo "${HOME}/go/bin" >> $GITHUB_PATH
 
-      - name: Run go-semantic-release (auto‑tag & release notes)
+      - name: Run go-semantic-release (tag + release)
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          semantic-release || test $? -eq 65
+          semantic-release || test $? -eq 65  # prevent fail if no release needed
 
   goreleaser:
     if: startsWith(github.ref, 'refs/tags/v')
